sonar.projectKey=FoodLabelFlow
sonar.projectName=FoodLabelFlow
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes
sonar.exclusions=**/node_modules/**,**/dist/**,bootstrap_inputs/**,.stage0/**
