import { expect, test } from '@playwright/test'
test('creates, publishes and preserves old content through the full stack', async ({ page,request }) => {
  test.skip(process.env.LIVE_WRITES !== '1', 'Explicit opt-in required for writes to local course data')
  const productId='prod_usda_1106285'
  const before=await (await request.get('/api/catalog/products/'+productId)).json()
  const old=await (await request.get('/api/catalog/formulas/'+before.current_formula_version_id)).json()
  await page.goto('/formulas')
  await page.getByRole('button',{name:'Create formula preview'}).click()
  await page.getByLabel('Product *',{exact:true}).selectOption(productId)
  await page.getByLabel('Supplier material *').selectOption('mat_chocolate_base')
  await page.getByLabel('Specification version *').selectOption('spec_chocolate_v1')
  await page.getByLabel('Quantity (optional)').fill('12.5')
  await page.getByLabel('Unit (optional)').fill('kg')
  await page.getByRole('button',{name:'Preview formula',exact:true}).click()
  await page.getByRole('checkbox',{name:'Enable local demo identity for this form'}).check()
  await page.getByRole('button',{name:'Save draft',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('Draft saved to the server')
  await page.getByRole('button',{name:'Publish formula',exact:true}).click()
  await page.getByRole('button',{name:'Confirm publication',exact:true}).click()
  await expect(page.getByText(/published successfully/)).toBeVisible()
  await page.getByRole('button',{name:'Refresh server history'}).click()
  await expect(page.getByRole('region',{name:'Formula history'})).toContainText('RELEASED')
  const after=await (await request.get('/api/catalog/products/'+productId)).json()
  expect(after.current_formula_version_id).not.toBe(before.current_formula_version_id)
  const preserved=await (await request.get('/api/catalog/formulas/'+before.current_formula_version_id)).json()
  expect(preserved.items).toEqual(old.items)
  expect(preserved.released_at).toEqual(old.released_at)
  await page.getByRole('button',{name:'Close preview'}).click()
  await page.reload()
  await page.getByRole('textbox',{name:'Search products'}).fill('1106285')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.screenshot({path:'test-results/live-published.png',fullPage:true})
})
