import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { BrowserRouter, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Box, Check, ChevronLeft, ChevronRight, CircleHelp, ClipboardCheck, Database, FileText, FlaskConical, GitBranch, Layers3, LayoutDashboard, Menu, Package, Search, ShieldCheck, Truck, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import data from '@/data/seed-preview.json'
import { HealthPage } from './pages/HealthPage'

const navigation = [
  { path: '/', label: '工作概览', icon: LayoutDashboard },
  { path: '/suppliers', label: '供应商', icon: Truck },
  { path: '/materials', label: '物料与规格', icon: Layers3 },
  { path: '/products', label: '产品目录', icon: Package },
  { path: '/formulas', label: '配方版本', icon: FlaskConical },
  { path: '/labels', label: '标签管理', icon: FileText },
  { path: '/impact', label: '变更影响', icon: GitBranch },
  { path: '/reviews', label: '审核工作台', icon: ClipboardCheck },
]
type Product = typeof data.product[number]
type Material = typeof data.supplier_material[number]
const groups: Record<string, string> = { NO_ACTION_BASELINE_SOY: '已声明大豆', REVIEW_REQUIRED_BASELINE_NO_SOY: '未声明大豆', NEGATIVE_CONTROL_NO_CHOCOLATE: '不含巧克力物料' }
const groupColors: Record<string, string> = { NO_ACTION_BASELINE_SOY: 'teal', REVIEW_REQUIRED_BASELINE_NO_SOY: 'violet', NEGATIVE_CONTROL_NO_CHOCOLATE: 'blue' }
const short = (text: string) => text.length > 52 ? `${text.slice(0, 52)}…` : text
function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section> }
function SectionHead({ title, caption, action }: { title: string; caption?: string; action?: ReactNode }) { return <div className="section-head"><div><h2>{title}</h2>{caption && <p>{caption}</p>}</div>{action}</div> }
function SourceBadge() { return <Badge variant="outline" className="source-badge"><Database size={12} /> 基线预览</Badge> }
function ReadOnlyNotice() { return <div className="source-notice"><Database size={15} /><span>当前展示数据库种子文件的只读快照，非实时业务数据。创建、发布与审核将在对应接口接入后开放。</span></div> }
function ProductGlyph({ index = 0 }: { index?: number }) { return <span className={`product-glyph tone-${index % 4}`}><Package size={21} strokeWidth={1.5} /></span> }
function exportProducts(products: Product[]) {
  const fields = ['product_id', 'product_description', 'brand_owner', 'fixture_group'] as const
  const csv = '\ufeff' + [fields.join(','), ...products.map(p => fields.map(f => `"${String(p[f]).replaceAll('"', '""')}"`).join(','))].join('\r\n')
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
  const a = document.createElement('a'); a.href = url; a.download = 'spectrace-seed-preview.csv'; a.click(); URL.revokeObjectURL(url)
}
function ProductDetails({ product, close }: { product: Product | null; close: () => void }) {
  const formula = data.formula_version.find(f => f.product_id === product?.product_id)
  const items = data.formula_item.filter(f => f.formula_version_id === formula?.formula_version_id)
  return <Dialog open={!!product} onOpenChange={open => !open && close()}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>产品与配方追溯</DialogTitle><DialogDescription>种子数据快照 · 历史与版本只读展示</DialogDescription></DialogHeader>{product && <>
    <div className="detail-product"><ProductGlyph /><div><h3>{product.product_description}</h3><p>{product.brand_owner}</p><code>{product.product_id}</code></div></div>
    <Tabs defaultValue="formula"><TabsList><TabsTrigger value="formula">配方与物料</TabsTrigger><TabsTrigger value="history">版本历史</TabsTrigger><TabsTrigger value="source">数据来源</TabsTrigger></TabsList>
      <TabsContent value="formula"><div className="detail-summary"><span>配方 V{formula?.version_number ?? '—'}</span><Badge variant="outline">{formula?.lifecycle_status ?? '未知'}</Badge><span>基线当前版本</span></div><div className="trace-list">{items.map((item, i) => { const material = data.supplier_material.find(m => m.supplier_material_id === item.supplier_material_id); const supplier = data.supplier.find(s => s.supplier_id === material?.supplier_id); return <div className="trace-row" key={item.formula_item_id}><span className="step-index">{i + 1}</span><div><strong>{material?.material_name}</strong><p>{supplier?.supplier_name}</p><code>{item.specification_version_id}</code></div><Badge variant="outline">规格 V{data.ingredient_specification_version.find(s => s.specification_version_id === item.specification_version_id)?.version_number}</Badge></div> })}</div></TabsContent>
      <TabsContent value="history"><div className="history-entry"><span className="history-dot"/><div><h3>V{formula?.version_number} · 已发布</h3><p>{formula?.released_at} · {formula?.released_by_user_id}</p><code>{formula?.formula_version_id}</code><p>基线快照只有此版本。实时版本历史尚未接入。</p></div></div></TabsContent>
      <TabsContent value="source"><div className="source-detail"><h3>公开产品记录</h3><p>USDA FoodData Central · FDC ID {product.fdc_id}</p><p>来源标识：{product.data_provenance_id}</p><h3>原始配料文本</h3><p>{product.source_ingredients_text}</p><p>供应商、物料和配方关联为课程项目构造的演示关系，不代表该品牌的真实供应链。</p></div></TabsContent>
    </Tabs><div className="dialog-bottom"><span>只读基线 · V3__baseline_seed.sql</span><Button variant="outline" onClick={close}>关闭</Button></div>
  </>}</DialogContent></Dialog>
}
function ProductTable({ products, onSelect, compact = false }: { products: Product[]; onSelect: (p: Product) => void; compact?: boolean }) {
  return <div className="table-scroll"><table><thead><tr><th>产品名称</th><th>品牌 / 所有者</th><th>配方版本</th>{!compact && <th>基线分组</th>}<th><span className="sr-only">操作</span></th></tr></thead><tbody>{products.map((p, i) => <tr key={p.product_id}><td><button className="product-cell" onClick={() => onSelect(p)}><ProductGlyph index={i}/><span><strong title={p.product_description}>{short(p.product_description)}</strong><small>FDC {p.fdc_id}</small></span></button></td><td><span className="brand-cell">{p.brand_owner}</span></td><td><span className="version-chip">V1</span><span className="released-dot"/> 已发布</td>{!compact && <td><span className={`group-tag ${groupColors[p.fixture_group]}`}>{groups[p.fixture_group]}</span></td>}<td><Button variant="ghost" size="icon" aria-label={`查看 ${p.product_description}`} onClick={() => onSelect(p)}><ArrowUpRight size={17}/></Button></td></tr>)}</tbody></table>{products.length === 0 && <div className="empty-search"><Search/><h3>没有匹配的产品</h3><p>试试其他名称、品牌或 FDC 编号。</p></div>}</div>
}
function Overview() {
  const navigate = useNavigate(); const [selected, setSelected] = useState<Product | null>(null)
  const [chart, setChart] = useState<'materials' | 'groups'>('materials')
  const bars = chart === 'materials' ? data.supplier_material.map(m => ({ name: m.material_name.replace(' Base', ''), count: new Set(data.formula_item.filter(f => f.supplier_material_id === m.supplier_material_id).map(f => f.formula_version_id)).size })) : Object.entries(groups).map(([key, name]) => ({ name, count: data.product.filter(p => p.fixture_group === key).length }))
  return <><div className="page-title"><div><div className="eyebrow">YOUR WORKSPACE, AT A GLANCE</div><h1>工作概览 <span className="hello-dot"/></h1><p>从原料到标签，每一个版本都有迹可循。</p></div><Button variant="outline" onClick={() => exportProducts(data.product)}><ArrowDownToLine size={16}/> 导出基线</Button></div><ReadOnlyNotice/>
    <div className="metrics-grid">{[{label:'产品档案', value:data.product.length, unit:'个产品', icon:Package, note:'已关联配方版本'}, {label:'供应商', value:data.supplier.length, unit:'家供应商', icon:Truck, note:'项目演示供应链'}, {label:'供应商物料', value:data.supplier_material.length, unit:'种物料', icon:Layers3, note:'规格版本可追溯'}, {label:'配方版本', value:data.formula_version.length, unit:'个版本', icon:FlaskConical, note:'基线已发布版本'}].map((metric,i) => <Panel key={metric.label} className={`metric ${i===0?'metric-featured':''}`}><div className="metric-top"><span>{metric.label}</span><metric.icon size={20}/></div><div className="metric-value">{metric.value}<span>{metric.unit}</span></div><div className="metric-note"><span className="tiny-dot"/>{metric.note}</div></Panel>)}</div>
    <div className="overview-charts"><Panel><SectionHead title="供应链数据概览" caption="配方引用分布 · 数据库基线" action={<div className="segmented"><button className={chart==='materials'?'active':''} onClick={() => setChart('materials')}>按物料</button><button className={chart==='groups'?'active':''} onClick={() => setChart('groups')}>按分组</button></div>}/><div className="chart-summary"><strong>{chart === 'materials' ? data.formula_item.length : data.product.length}</strong><span>{chart==='materials'?'条配方物料引用':'个基线产品'}</span><Badge variant="outline">V3 基线</Badge></div><div className="bar-chart" role="img" aria-label={bars.map(b=>`${b.name}: ${b.count}`).join('；')}><div className="axis-labels">{[60,45,30,15,0].map(n=><span key={n}>{n}</span>)}</div><div className="bars">{bars.map((b,i)=><div className="bar-column" key={b.name}><div className={`bar bar-${i}`} style={{height:`${b.count / 60 * 100}%`}}><span>{b.count}</span></div><span className="bar-label">{b.name}</span></div>)}</div></div></Panel>
    <Panel><SectionHead title="演示数据分组" caption="分组不代表已执行的影响分析"/><div className="donut-layout"><div className="donut" role="img" aria-label="三组基线数据各20个产品"><div><strong>60</strong><span>基线产品</span></div></div><div className="donut-legend">{Object.entries(groups).map(([key,label],i)=><div key={key}><span className={`legend-dot dot-${i}`}/><span>{label}</span><strong>{data.product.filter(p=>p.fixture_group===key).length}</strong></div>)}</div></div></Panel></div>
    <div className="overview-bottom"><Panel><SectionHead title="产品档案" caption="查看产品、配方和上游规格" action={<Button variant="ghost" onClick={()=>navigate('/products')}>全部产品 <ArrowRight size={16}/></Button>}/><ProductTable products={data.product.slice(0,4)} compact onSelect={setSelected}/></Panel><Panel className="journey-panel"><span className="journey-icon"><GitBranch size={24}/></span><h2>让变更有据可查</h2><p>沿着物料与配方的关联，查看产品使用的具体规格版本。</p><div className="mini-journey"><span>原料规格</span><span>配方版本</span><span>产品档案</span></div><Button onClick={()=>navigate('/formulas')}>探索配方追溯 <ArrowUpRight size={16}/></Button><small>标签与审核功能将在后续阶段接入</small></Panel></div><ProductDetails product={selected} close={()=>setSelected(null)}/></>
}
function Catalog({ formulas = false }: { formulas?: boolean }) {
  const [query,setQuery]=useState(''); const [group,setGroup]=useState('all'); const [page,setPage]=useState(1); const [selected,setSelected]=useState<Product|null>(null)
  const filtered=useMemo(()=>data.product.filter(p=>(group==='all'||p.fixture_group===group)&&`${p.product_description} ${p.brand_owner} ${p.fdc_id}`.toLowerCase().includes(query.toLowerCase())),[group,query]); const total=Math.max(1,Math.ceil(filtered.length/8))
  return <><div className="page-title"><div><div className="eyebrow">{formulas?'VERSIONED & TRACEABLE':'YOUR PRODUCT LIBRARY'}</div><h1>{formulas?'配方版本':'产品目录'}</h1><p>{formulas?'查看每个产品的物料引用与配方历史。':'集中查看产品档案与上游供应链关联。'}</p></div><Button variant="outline" onClick={()=>exportProducts(filtered)}><ArrowDownToLine size={16}/> 导出当前列表</Button></div><ReadOnlyNotice/><Panel><div className="catalog-toolbar"><div className="search-box"><Search size={17}/><Input aria-label="搜索产品" placeholder="搜索产品、品牌或 FDC 编号…" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><select aria-label="筛选基线分组" value={group} onChange={e=>{setGroup(e.target.value);setPage(1)}}><option value="all">全部分组</option>{Object.entries(groups).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><span className="results-count">{filtered.length} 个产品</span></div><ProductTable products={filtered.slice((page-1)*8,page*8)} onSelect={setSelected}/><div className="pagination"><span>第 {page} / {total} 页 · 基线只读数据</span><div><Button variant="outline" size="icon" aria-label="上一页" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></Button><Button variant="outline" size="icon" aria-label="下一页" disabled={page>=total} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></Button></div></div></Panel>{formulas && <div className="availability-note"><ShieldCheck size={18}/><div><strong>创建与发布暂未开放</strong><p>配方接口接入后，可在这里创建新版本；已发布版本始终保留历史。</p></div></div>}<ProductDetails product={selected} close={()=>setSelected(null)}/></>
}
function Materials({ suppliers = false }: { suppliers?: boolean }) {
  const [selected,setSelected]=useState<Material|null>(null); const [query,setQuery]=useState('')
  const filtered=data.supplier_material.filter(m=>`${m.material_name} ${m.material_code}`.toLowerCase().includes(query.toLowerCase()))
  return <><div className="page-title"><div><div className="eyebrow">SUPPLY CHAIN DIRECTORY</div><h1>{suppliers?'供应商':'物料与规格'}</h1><p>从供应商到具体规格，保留每一层关联。</p></div><SourceBadge/></div><ReadOnlyNotice/>{suppliers?<div className="supplier-grid">{data.supplier.map((s,i)=><Panel key={s.supplier_id} className="supplier-card"><span className={`supplier-icon tone-${i}`}><Truck size={25}/></span><Badge variant="outline">项目演示</Badge><h2>{s.supplier_name}</h2><p>{s.supplier_code}</p><div className="supplier-stats"><strong>{data.supplier_material.filter(m=>m.supplier_id===s.supplier_id).length}</strong><span>关联物料</span></div>{data.supplier_material.filter(m=>m.supplier_id===s.supplier_id).map(m=><button className="material-link" key={m.supplier_material_id} onClick={()=>setSelected(m)}><span>{m.material_name}</span><ArrowUpRight size={16}/></button>)}</Panel>)}</div>:<Panel><div className="catalog-toolbar"><div className="search-box"><Search size={17}/><Input aria-label="搜索物料" placeholder="搜索物料名称或编号…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="results-count">{filtered.length} 种物料</span></div><div className="table-scroll"><table><thead><tr><th>供应商物料</th><th>供应商</th><th>规格版本</th><th>状态</th><th>详情</th></tr></thead><tbody>{filtered.map((m,i)=><tr key={m.supplier_material_id}><td><button className="product-cell" onClick={()=>setSelected(m)}><ProductGlyph index={i}/><span><strong>{m.material_name}</strong><small>{m.material_code}</small></span></button></td><td>{data.supplier.find(s=>s.supplier_id===m.supplier_id)?.supplier_name}</td><td>V1</td><td><span className="group-tag teal">已发布</span></td><td><Button variant="ghost" size="icon" aria-label={`查看 ${m.material_name}`} onClick={()=>setSelected(m)}><ArrowUpRight size={17}/></Button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty-search">没有匹配的物料</div>}</div></Panel>}
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{selected?.material_name}</DialogTitle><DialogDescription>物料规格与上游成分 · 基线快照</DialogDescription></DialogHeader>{selected&&<><p>{selected.material_description}</p><code>{selected.supplier_material_id}</code>{data.ingredient_specification_version.filter(s=>s.supplier_material_id===selected.supplier_material_id).map(s=><div key={s.specification_version_id}><div className="detail-summary"><strong>规格 V{s.version_number}</strong><Badge variant="outline">{s.lifecycle_status}</Badge></div><p className="muted">生效日期 {s.effective_date}</p><div className="trace-list">{data.spec_component.filter(c=>c.specification_version_id===s.specification_version_id).map((c,i)=><div className="trace-row" key={c.spec_component_id}><span className="step-index">{i+1}</span><div><strong>{c.raw_phrase}</strong><p>{c.ingredient_id}</p></div><Check size={16}/></div>)}</div></div>)}<div className="dialog-bottom"><span>来源：PROJECT_SEEDED</span><Button variant="outline" onClick={()=>setSelected(null)}>关闭</Button></div></>}</DialogContent></Dialog>
  </>
}
function Upcoming({ kind }: { kind:'labels'|'impact'|'reviews' }) {
  const content={labels:{title:'标签管理', subtitle:'让每一份声明，都对应准确的配方版本。',icon:FileText,steps:['关联配方版本','编辑标签声明','校验与提交'],stage:'Sprint 2',link:'/formulas',cta:'查看配方版本'},impact:{title:'变更影响',subtitle:'识别原料变化影响的产品，区分无需操作和待复核。',icon:GitBranch,steps:['选择变更来源','分析受影响产品','创建必要的审查任务'],stage:'Sprint 3',link:'/materials',cta:'查看物料与规格'},reviews:{title:'审核工作台',subtitle:'让标签经过校验、独立审核和受控发布。',icon:ClipboardCheck,steps:['接收审查任务','独立审核与批准','发布并保留旧版本'],stage:'Sprint 3',link:'/products',cta:'查看产品档案'}}[kind]
  const navigate=useNavigate()
  return <><div className="page-title"><div><div className="eyebrow">CONTROLLED WORKFLOW</div><h1>{content.title}</h1><p>{content.subtitle}</p></div><Badge variant="outline">{content.stage}</Badge></div><Panel className="upcoming"><span className="upcoming-icon"><content.icon size={35}/></span><h2>工作区已规划，业务接口尚未接入</h2><p>这里暂不显示任务数量或处理结果。你可以先浏览已经提供的产品与配方基线。</p><div className="workflow-steps">{content.steps.map((s,i)=><div key={s}><span>{i+1}</span><strong>{s}</strong></div>)}</div><Button onClick={()=>navigate(content.link)}>{content.cta}<ArrowRight size={16}/></Button></Panel></>
}
function Shell() {
  const [mobile,setMobile]=useState(false); const [help,setHelp]=useState(false); const location=useLocation(); const navigate=useNavigate()
  useEffect(()=>{setMobile(false)},[location.pathname])
  const active=navigation.find(n=>n.path===location.pathname)
  return <div className="app-shell"><a href="#main" className="skip-link">跳到主要内容</a><header className="topbar"><div className="wordmark"><span className="logo"><Layers3 size={23}/></span>SpecTrace<span className="workspace-label">食品标签工作空间</span></div><div className="topbar-right"><span className="environment"><span/>本地工作空间</span><button aria-label="使用帮助" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button><span className="topbar-divider"/><span className="avatar">XF</span></div></header>
    {mobile&&<button className="mobile-overlay" aria-label="关闭导航遮罩" onClick={()=>setMobile(false)}/>}
    <aside className={`sidebar ${mobile?'is-open':''}`}><div className="workspace-switch"><span className="workspace-icon"><Box size={21}/></span><div><strong>FoodLabelFlow</strong><small>TEAM 16 · SWE5006</small></div><button className="mobile-close" aria-label="关闭导航" onClick={()=>setMobile(false)}><X size={18}/></button></div><p className="nav-section-label">工作空间</p><nav aria-label="主导航">{navigation.map((n,i)=><NavLink end={n.path==='/'} to={n.path} key={n.path} className={({isActive})=>`nav-item ${isActive?'active':''}`}><n.icon size={19}/><span>{n.label}</span>{i>4&&<span className="nav-dot"/>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="version-note"><span className="version-icon"><ShieldCheck size={21}/></span><strong>版本始终可追溯</strong><p>保留过去，准确管理每一次变化。</p></div><NavLink to="/health" className={({isActive})=>`nav-item ${isActive?'active':''}`}><Activity size={18}/><span>系统状态</span></NavLink><button className="nav-item" onClick={()=>setHelp(true)}><CircleHelp size={18}/><span>使用指南</span></button><div className="user-card"><span className="avatar">XF</span><div><strong>Xu Feiyang</strong><small>M3 · 本地预览身份</small></div></div></div></aside>
    <div className="main-shell"><div className="contextbar"><div className="breadcrumb"><button className="mobile-toggle" aria-label="展开导航" onClick={()=>setMobile(true)}><Menu size={20}/></button><span>工作空间</span><ChevronRight size={14}/><strong>{active?.label??(location.pathname==='/health'?'系统状态':'页面')}</strong></div><button className="quick-search" onClick={()=>navigate('/products')}><Search size={16}/><span>搜索产品与配方</span></button></div><main id="main"><Routes><Route path="/" element={<Overview/>}/><Route path="/products" element={<Catalog/>}/><Route path="/formulas" element={<Catalog formulas/>}/><Route path="/suppliers" element={<Materials suppliers/>}/><Route path="/materials" element={<Materials/>}/><Route path="/labels" element={<Upcoming kind="labels"/>}/><Route path="/impact" element={<Upcoming kind="impact"/>}/><Route path="/reviews" element={<Upcoming kind="reviews"/>}/><Route path="/health" element={<HealthPage/>}/><Route path="*" element={<Panel className="upcoming"><h1>页面不存在</h1><Button onClick={()=>navigate('/')}>返回工作概览</Button></Panel>}/></Routes><footer className="page-footer"><span>SpecTrace · Food label change control</span><span>本地预览 / 单市场 MVP</span></footer></main></div>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>欢迎使用 SpecTrace</DialogTitle><DialogDescription>当前版本支持浏览基线产品、物料和配方追溯。</DialogDescription></DialogHeader><ol className="help-list"><li>在产品目录中搜索名称、品牌或编号，点击产品查看配方。</li><li>在详情弹窗中切换配方、版本历史与数据来源。</li><li>供应商和物料页面可查看具体规格和成分。</li><li>业务数据为 V3 种子快照；只有系统状态页读取实时健康接口。</li><li>本地预览身份不代表已登录，创建、发布和审批尚未开放。</li></ol></DialogContent></Dialog>
  </div>
}
export default function App() { return <BrowserRouter><Shell/></BrowserRouter> }
